src/Entity/Releve.php
<?php

namespace App\Entity;

use App\Repository\ReleveRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Random\RandomException;

#[ORM\Entity(repositoryClass: ReleveRepository::class)]
class Releve
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'releves')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Lieu $lieu = null;

    #[ORM\Column(length: 17)]
    private ?string $releve_brut = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getReleveBrut(): ?string
    {
        return $this->releve_brut;
    }

    public function setReleveBrut(string $releve_brut): static
    {
        $this->releve_brut = $releve_brut;

        return $this;
    }

    /**
     * @throws RandomException
     */
    public function generateTable(): array
    {
        $matrix = [];
        $releve_brut = explode('/', $this->getReleveBrut());
        $releve_brut = array_map(fn($x) => (int) $x, $releve_brut);

        for($y = 0; $y < 3; $y++) {
            $matrix[$y] = [];
            for($x = 0; $x < 3; $x++) {
                $matrix[$y][$x] = [];

                for($i = 0; $i < $releve_brut[$y * 3 + $x]; $i++) {
                    $index = random_int(0, 8);
                    while(in_array($index, $matrix[$y][$x])) {
                        $index = random_int(0, 8);
                    }

                    $matrix[$y][$x][] = $index;
                }
            }
        }

        return $matrix;
    }
}

src/Form/ReleveType.php
<?php

namespace App\Form;

use App\Entity\Lieu;
use App\Entity\Releve;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReleveType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('releve_brut')
            ->add('lieu', EntityType::class, [
                'class' => Lieu::class,
                'choice_label' => 'nom',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Releve::class,
        ]);
    }
}

src/Controller/RelevesController.php
<?php

namespace App\Controller;

use App\Entity\Releve;
use App\Form\ReleveType;
use App\Repository\ReleveRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RelevesController extends AbstractController
{
    #[Route('/', name: 'app_releves')]
    public function index(Request $request, ReleveRepository $repository, EntityManagerInterface $em): Response
    {
        $releve = new Releve();
        $form = $this->createForm(ReleveType::class);
        $form->setData($releve);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $releve = $form->getData();
            $em->persist($releve);
            $em->flush();

            return $this->redirectToRoute('app_releves');
        }

        return $this->render('releves/index.html.twig', [
            'releves' => $repository->findAll(),
            'form_releve' => $form->createView(),
        ]);
    }

    #[Route('/releves/{id}/edit', name: 'app_releves_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Releve $releve, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(ReleveType::class, $releve);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $em->persist($releve);
            $em->flush();

            return $this->redirectToRoute('app_releves');
        }

        return $this->render('releves/edit.html.twig', [
            'form_releve' => $form->createView(),
        ]);
    }

    #[Route('/releves/{id}/delete', name: 'app_releves_delete', methods: ['POST'])]
    public function delete(Request $request, Releve $releve, EntityManagerInterface $em): Response
    {
        if($this->isCsrfTokenValid('delete' . $releve->getId(), $request->request->get('_csrf_token'))) {
            $em->remove($releve);
            $em->flush();
        }

        return $this->redirectToRoute('app_releves');
    }
}

templates/releves/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un relevé{% endblock %}

{% block body %}
    {{ form_start(form_releve) }}
        {{ form_row(form_releve.date) }}
        {{ form_row(form_releve.lieu) }}
        <a href="{{ path('app_lieux') }}" class="btn btn-primary">Administrer les lieux</a>
        {{ form_row(form_releve.releve_brut) }}
        <button class="btn btn-primary">Ajouter</button>
    {{ form_end(form_releve) }}
{% endblock %}

templates/releves/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Herbiers{% endblock %}

{% block body %}
    <h1>Herbiers</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Lieu</th>
                <th>Relevé Brut</th>
                <th>Tableau</th>
                <th>Visualisation</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for releve in releves %}
            <tr>
                <td>{{ releve.date|date('d/m/Y') }}</td>
                <td>{{ releve.lieu.nom }}</td>
                <td>{{ releve.releveBrut }}</td>
                <td>
                    <table class="tableau">
                        <tbody>
                            <tr>
                                <td>{{ releve.releveBrut|split('/')[0] }}</td>
                                <td>{{ releve.releveBrut|split('/')[1] }}</td>
                                <td>{{ releve.releveBrut|split('/')[2] }}</td>
                            </tr>
                            <tr>
                                <td>{{ releve.releveBrut|split('/')[3] }}</td>
                                <td>{{ releve.releveBrut|split('/')[4] }}</td>
                                <td>{{ releve.releveBrut|split('/')[5] }}</td>
                            </tr>
                            <tr>
                                <td>{{ releve.releveBrut|split('/')[6] }}</td>
                                <td>{{ releve.releveBrut|split('/')[7] }}</td>
                                <td>{{ releve.releveBrut|split('/')[8] }}</td>
                            </tr>
                        </tbody>
                    </table>
                </td>
                <td>
                    <table class="tableauVisu">
                        {% set visu = releve.generateTable %}
                        <tbody>
                            {% for row in visu %}
                                <tr>
                                    {% for cell in row %}
                                        <td>
                                            <table class="petitTableau">
                                                <tbody>
                                                {% for y in range(0, 2) %}
                                                    <tr>
                                                        {% for x in range(0, 2) %}
                                                            {% if (y * 3 + x) in cell %}
                                                                <td class="vert"></td>
                                                            {% else %}
                                                                <td></td>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td>
                <td>
                    <form method="post" action="{{ path('app_releves_delete', {'id': releve.id}) }}" onsubmit="confirm('Voulez-vous réellement supprimer ce relevé ?')">
                        <a class="btn btn-primary" href="{{ path('app_releves_edit', {'id': releve.id}) }}">Modifier</a>
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token('delete' ~ releve.id) }}">
                        <button type="submit" class="btn btn-danger">Supprimer</button>
                    </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Aucun herbier trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <hr>
    <h1>Ajouter un relevé</h1>

    {{ form_start(form_releve) }}
        {{ form_row(form_releve.date) }}
        {{ form_row(form_releve.lieu) }}
        <a href="{{ path('app_lieux') }}" class="btn btn-primary">Administrer les lieux</a>
        {{ form_row(form_releve.releve_brut) }}
        <button class="btn btn-primary">Ajouter</button>
    {{ form_end(form_releve) }}
{% endblock %}